#!/bin/bash

# compiles demo code into ROMPROG
printf "%s\n%s\n%s\n" "$(head -n 27 <vhdl/ROMPROG.vhd)" "$(./asrisc assembler/opcodes.js demo/demo.asm 2>&1)" "$(tail -n 10 < vhdl/ROMPROG.vhd)" > vhdl/ROMPROG.vhd

# compiles demo data into RAMDoublePort
printf "%s\n%s\n%s\n" "$(head -n 38 <vhdl/RAMDoublePort.vhd)" "$(./asrisc assembler/data.js demo/data.asm 2>&1)" "$(tail -n 31 < vhdl/RAMDoublePort.vhd)" > vhdl/RAMDoublePort.vhd
