######################################################################
# Automatically generated by qmake (2.01a) Thu Feb 11 12:32:30 2010
######################################################################

TEMPLATE = app
TARGET = assembler
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += debug

QT -= gui
QT += script

# Input
SOURCES += main.cpp
